[[redirects]]
  from = "/topics/toolchain-types_2.html"
  to = "/topics/Tools-and-toolchains/toolchain-types/"
  status = 301
  force = false
  conditions = {Language = ["en","es"], Country = ["US"]}


[[redirects]]
  from = "/topics/toolchain-types.html"
  to = "/topics/Tools-and-toolchains/toolchain-types/"
  status = 301
  force = false
  conditions = {Language = ["en","es"], Country = ["US"]}


[[redirects]]
  from = "/topics/about-api-docs.html"
  to = "/topics/about-api-docs/"
  status = 301
  force = false
  conditions = {Language = ["en","es"], Country = ["US"]}


[[redirects]]
  from = "/topics/writer-resources.html"
  to = "/topics/writer-resources/"
  status = 301
  force = false
  conditions = {Language = ["en","es"], Country = ["US"]}

[[redirects]]
  from = "/topics/about-this-site.html "
  to = "/topics/about-this-site/"
  status = 301
  force = false
  conditions = {Language = ["en","es"], Country = ["US"]}

[[redirects]]
  from = "/topics/about-the-author.html"
  to = "/topics/about-the-author/"
  status = 301
  force = false
  conditions = {Language = ["en","es"], Country = ["US"]}













